In [72]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

In [73]:
df=pd.read_csv('agr_en_train.csv',sep=',',names=['id','comment','category'])

In [74]:
df.head()

id  \
0  facebook_corpus_msr_1723796   
1   facebook_corpus_msr_466073   
2  facebook_corpus_msr_1493901   
3   facebook_corpus_msr_405512   
4  facebook_corpus_msr_1521685   

                                             comment category  
0  Well said sonu..you have courage to stand agai...      OAG  
1  Most of Private Banks ATM's Like HDFC, ICICI e...      NAG  
2     Now question is, Pakistan will adhere to this?      OAG  
3  Pakistan is comprised of fake muslims who does...      OAG  
4  ??we r against cow slaughter,so of course it w...      NAG

In [75]:
len(df)

11999

In [76]:
len(df[df.category=='NAG'])

5051

In [77]:
len(df[df.category=='CAG'])

4240

In [78]:
len(df[df.category=='OAG'])

2708

In [79]:
df.loc[df["category"]=='NAG',"category",]=0
df.loc[df["category"]=='CAG',"category",]=1
df.loc[df["category"]=='OAG',"category",]=2

In [80]:
df.head()

id  \
0  facebook_corpus_msr_1723796   
1   facebook_corpus_msr_466073   
2  facebook_corpus_msr_1493901   
3   facebook_corpus_msr_405512   
4  facebook_corpus_msr_1521685   

                                             comment category  
0  Well said sonu..you have courage to stand agai...        2  
1  Most of Private Banks ATM's Like HDFC, ICICI e...        0  
2     Now question is, Pakistan will adhere to this?        2  
3  Pakistan is comprised of fake muslims who does...        2  
4  ??we r against cow slaughter,so of course it w...        0

In [81]:
len(df[df.category==0])

5051

In [82]:
df_x=df['comment']
df_y=df['category']

In [83]:
df_x

0        Well said sonu..you have courage to stand agai...
1        Most of Private Banks ATM's Like HDFC, ICICI e...
2           Now question is, Pakistan will adhere to this?
3        Pakistan is comprised of fake muslims who does...
4        ??we r against cow slaughter,so of course it w...
5        Wondering why Educated Ambassador is strugglin...
6        How does inflation react to all the after shoc...
7        Not good job.....this guis creating a problem ...
8        This is a false news Indian media is simply mi...
9        no permanent foes, no permanent friends. inter...
10       Deepak Kumar Sharma Saab...chalo aap ki Ye baa...
11       Communist parties killed lacks of opponents in...
12       Why you guys counter the modi govt decisions, ...
13                Rss is 3 time ban terrorist organization
14       No\r\nSame acting ll be there ..\r\nbut we ll ...
15       Happy Diwali.!!let's wish the next one year he...
16       Lolz... He said he is gonna employ large numbe.

In [84]:
cv = TfidfVectorizer(min_df=1,stop_words='english')

In [85]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [86]:
x_traincv = cv.fit(["Hi How are you buddy I am good you are badHow are you doing","Hi what's up","Wow that's awesome"])

In [87]:
x_traincv.transform(["Hi How are you buddy I am good you are badHow are you doing","Hi what's up","Wow that's awesome"]).toarray()

array([[0.        , 0.46735098, 0.46735098, 0.46735098, 0.46735098,
        0.35543247, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678]])

In [88]:
cv.get_feature_names()

['awesome', 'badhow', 'buddy', 'doing', 'good', 'hi', 'wow']

In [89]:
cv1 = TfidfVectorizer(min_df=1,stop_words='english')


In [90]:
x_traincv=cv1.fit_transform(x_train)

In [91]:
a=x_traincv.toarray()

In [92]:
a[0]


array([0., 0., 0., ..., 0., 0., 0.])

In [93]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [94]:
cv1.inverse_transform(a[0])

[array(['ago', 'best', 'day', 'favorite', 'great', 'interested', 'job',
        'long', 'nice', 'requirements', 'send', 'status'], dtype='<U127')]

In [95]:
for x in a[0]:
    if x>0:
        print(x)

0.28115400795088585
0.19774482778943026
0.37825200202430725
0.36602089256979065
0.18834171855955642
0.26846567511676306
0.2130361327375508
0.4000800653355819
0.2303889118131365
0.33924837127029916
0.23215828607233335
0.2640884018242798


In [96]:
x_train.iloc[0]

'Nice job in a while ago but never the best of my favorite part is a very long day at a very long day for you are interested please send us your requirements with you to see the status is a great'

In [97]:
mnb=MultinomialNB()

In [98]:
y_train=y_train.astype('int')

In [99]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [100]:
x_testcv=cv1.transform(x_test)

In [101]:
print(x_test)

4375           Is  this  English  version  of  desabhimani
7611     Thank you Anna for not joining AAP, Otherwise ...
8562     I don't understand you Muslim people don't liv...
9576     the idiot addresses his party leaders and give...
2752     Mr. KRK is not capable to understand the film ...
770      Well i can now see clearly bjp losing 2019 no ...
526      All benifits gone to pakistan . Leather produc...
6011                                               Cheater
2072     This ridiculous act.....it's illiterates peopl...
7855     The increase is a trap . Markets will fall big...
2916     Pakistan a rogue state because today Pakistani...
4275     Lakti Ningthou... Better is you to write the s...
2741     I mean look at that dress....it's like sweepin...
956      Change is inevitable. He has delivered his rol...
11905         No wonder most ISIS caders were from Kerala.
5778     Unfortunately all Kashmiri talent like shah Fa...
10063    Again he is lying, when Gurmehar already clari.

In [102]:
# ar=cv1.transform()

In [103]:
ar=np.array('Hello how are you? Guess you are fine!')

In [104]:
pred=mnb.predict(ar)

TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

In [ ]:
pred

In [ ]:
actual=np.array(y_test)

In [ ]:
pre


In [ ]:
for i in range(len(pred)):

In [ ]:
count=0

In [ ]:
for i in range(len(pred)):
    if pred[i]==actual[i]:
        count=count+1

In [ ]:
count

In [ ]:
count/len(pred)


In [ ]:
x_test.iloc[0]